import { SideBarContextProvider } from "@/provider/side-bar-provider";
import "./globals.css";
import type { Metadata } from "next";
import "react-toastify/ReactToastify.css";
import BodyLayout from "./components/body-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SideBarContextProvider>
      <html lang="en">
        <BodyLayout>{children}</BodyLayout>
      </html>
    </SideBarContextProvider>
  );
}
