import "./globals.css";
import type { Metadata } from "next";
import { Inter, Lato, Playfair_Display } from "next/font/google";
const lato = Lato({ weight: ["700", "400"], subsets: ["latin", "latin-ext"] });
const palyfair = Playfair_Display({
  weight: ["700", "600", "400"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        {children}
      </body>
    </html>
  );
}
